import type { Category, NodeKind, NodeSpec, PortDef } from '../engine/types';
import { BAL } from '../engine/balance';

// ---------------------------------------------------------------------------
// The infrastructure catalog. Every placeable node, its ports, its transform.
// Capacity is in weighted req/s; see capWeight for classes that cost more.
// Rival techs encode their real-world trade-off in broad strokes: MySQL is the
// cheap workhorse with weaker write concurrency, SQL Server is the strong
// engine with a licensing bill, Memcached is fast-and-dumb next to Redis, etc.
// ---------------------------------------------------------------------------

const P = (id: string, type: PortDef['type'], dir: PortDef['dir'], label: string): PortDef => ({
  id,
  type,
  dir,
  label,
});

export const CATEGORY_INFO: Record<Category, { label: string; color: string }> = {
  ingress: { label: 'Ingress / Network', color: '#58a6ff' },
  compute: { label: 'Compute', color: '#f0a44b' },
  data: { label: 'Data / Storage', color: '#a78bfa' },
  cache: { label: 'Cache / Edge', color: '#ec6ea5' },
  async: { label: 'Async / Queues', color: '#34d1bf' },
  observability: { label: 'Observability', color: '#7ce38b' },
  automation: { label: 'Automation', color: '#39c5cf' },
};

export const SPECS: Record<Exclude<NodeKind, 'zone'>, NodeSpec> = {
  users: {
    kind: 'users',
    name: 'Internet',
    short: 'WWW',
    category: 'ingress',
    blurb: 'Your users. Traffic originates here and grows with reputation. Cannot be removed.',
    docsUrl: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview',
    cost: 0,
    opCost: 0,
    capacity: 1e9,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [P('http-out', 'http', 'out', 'egress')],
    serves: [],
    forwards: {},
    special: 'source',
  },
  nginx: {
    kind: 'nginx',
    name: 'Nginx',
    short: 'NGX',
    category: 'ingress',
    blurb: 'Web server. Serves static files itself, proxies everything else upstream.',
    docsUrl: 'https://nginx.org/en/docs/',
    cost: 60,
    opCost: 0.04,
    capacity: 12,
    baseLatencyMs: 5,
    queueLen: 30,
    ports: [P('http-in', 'http', 'in', 'listen :80'), P('http-out', 'http', 'out', 'upstream')],
    serves: ['static'],
    forwards: { api: 'http', read: 'http', write: 'http', job: 'http' },
    zoneUnit: true,
  },
  lb: {
    kind: 'lb',
    name: 'Load Balancer',
    short: 'ELB',
    category: 'ingress',
    blurb: 'Managed balancer. Splits traffic across upstreams by available headroom — the smart way.',
    docsUrl: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/what-is-load-balancing.html',
    cost: 140,
    opCost: 0.05,
    capacity: 150,
    baseLatencyMs: 1,
    queueLen: 200,
    ports: [P('http-in', 'http', 'in', 'vip'), P('http-out', 'http', 'out', 'targets')],
    serves: [],
    forwards: { static: 'http', api: 'http', read: 'http', write: 'http', job: 'http' },
    smartSplit: true,
    special: 'lb',
  },
  haproxy: {
    kind: 'haproxy',
    name: 'HAProxy',
    short: 'HAP',
    category: 'ingress',
    blurb: 'Software balancer. Cheaper and higher raw throughput than a managed LB — but splits round-robin, blind to headroom.',
    docsUrl: 'https://docs.haproxy.org/',
    cost: 90,
    opCost: 0.03,
    capacity: 260,
    baseLatencyMs: 1,
    queueLen: 300,
    ports: [P('http-in', 'http', 'in', 'frontend'), P('http-out', 'http', 'out', 'backends')],
    serves: [],
    forwards: { static: 'http', api: 'http', read: 'http', write: 'http', job: 'http' },
    revGate: 100,
  },
  apigw: {
    kind: 'apigw',
    name: 'API Gateway',
    short: 'AGW',
    category: 'ingress',
    blurb: 'Rate-limits at the door: overload is shed as 429s (cheap) instead of timing out (costly).',
    docsUrl: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html',
    cost: 220,
    opCost: 0.08,
    capacity: 250,
    baseLatencyMs: 2,
    queueLen: 260,
    ports: [P('http-in', 'http', 'in', 'edge'), P('http-out', 'http', 'out', 'routes')],
    serves: [],
    forwards: { static: 'http', api: 'http', read: 'http', write: 'http', job: 'http' },
    research: 'gateway',
    special: 'apigw',
  },
  cdn: {
    kind: 'cdn',
    name: 'Cloudflare CDN',
    short: 'CDN',
    category: 'cache',
    blurb: 'Edge cache. Serves 92% of static and 30% of reads at the edge for a flat fee; misses hit your origin.',
    docsUrl: 'https://developers.cloudflare.com/cache/',
    cost: 300,
    opCost: 0.12,
    capacity: 1500,
    baseLatencyMs: 2,
    queueLen: 1500,
    ports: [P('http-in', 'http', 'in', 'edge'), P('http-out', 'http', 'out', 'origin')],
    serves: [],
    forwards: { static: 'http', api: 'http', read: 'http', write: 'http', job: 'http' },
    hitRate: { static: 0.92, read: 0.3 },
    research: 'cdn',
  },
  fastly: {
    kind: 'fastly',
    name: 'Fastly',
    short: 'FST',
    category: 'cache',
    blurb: 'Programmable edge. Instant purge means it dares to cache dynamic reads (50%) — and bills you per request.',
    docsUrl: 'https://www.fastly.com/documentation/',
    cost: 340,
    opCost: 0.1,
    capacity: 1200,
    baseLatencyMs: 2,
    queueLen: 1200,
    ports: [P('http-in', 'http', 'in', 'edge'), P('http-out', 'http', 'out', 'origin')],
    serves: [],
    forwards: { static: 'http', api: 'http', read: 'http', write: 'http', job: 'http' },
    hitRate: { static: 0.9, read: 0.5 },
    perServeCost: 0.0005,
    research: 'cdn',
  },
  varnish: {
    kind: 'varnish',
    name: 'Varnish',
    short: 'VNH',
    category: 'cache',
    blurb: 'Self-hosted HTTP accelerator at your origin. No per-request fees — but no edge either; physics still applies.',
    docsUrl: 'https://varnish-cache.org/docs/',
    cost: 150,
    opCost: 0.06,
    capacity: 450,
    baseLatencyMs: 3,
    queueLen: 600,
    ports: [P('http-in', 'http', 'in', 'accept'), P('http-out', 'http', 'out', 'backend fetch')],
    serves: [],
    forwards: { static: 'http', api: 'http', read: 'http', write: 'http', job: 'http' },
    hitRate: { static: 0.85, read: 0.2 },
    research: 'caching',
  },
  s3: {
    kind: 's3',
    name: 'S3 Bucket',
    short: 'S3',
    category: 'data',
    blurb: 'Object storage. Serves static at any volume for a tiny per-request fee. Slow-ish alone; pair with a CDN.',
    docsUrl: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html',
    cost: 90,
    opCost: 0.02,
    capacity: 5000,
    baseLatencyMs: 45,
    queueLen: 4000,
    ports: [P('http-in', 'http', 'in', 'GET')],
    serves: ['static'],
    forwards: {},
    perServeCost: 0.0004,
    revGate: 300,
  },
  app: {
    kind: 'app',
    name: 'App Server',
    short: 'EC2',
    category: 'compute',
    blurb: 'Your Docker container on an EC2-style box. Completes API calls; reads/writes go out the DB port, heavy jobs out the async port.',
    docsUrl: 'https://docs.docker.com/get-started/',
    cost: 120,
    opCost: 0.1,
    capacity: 15,
    baseLatencyMs: 12,
    queueLen: 40,
    ports: [
      P('http-in', 'http', 'in', 'requests'),
      P('data-out', 'data', 'out', 'db pool'),
      P('jobs-out', 'jobs', 'out', 'enqueue'),
    ],
    serves: ['static', 'api'],
    forwards: { read: 'data', write: 'data', job: 'jobs' },
    capWeight: { static: 0.6 },
    zoneUnit: true,
  },
  spot: {
    kind: 'spot',
    name: 'Spot Instance',
    short: 'SPT',
    category: 'compute',
    blurb: 'The same box at 40% of the run cost — because the cloud can reclaim it any time. Run N+1 or eat the gaps.',
    docsUrl: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-instances.html',
    cost: 100,
    opCost: 0.04,
    capacity: 15,
    baseLatencyMs: 12,
    queueLen: 40,
    ports: [
      P('http-in', 'http', 'in', 'requests'),
      P('data-out', 'data', 'out', 'db pool'),
      P('jobs-out', 'jobs', 'out', 'enqueue'),
    ],
    serves: ['static', 'api'],
    forwards: { read: 'data', write: 'data', job: 'jobs' },
    capWeight: { static: 0.6 },
    zoneUnit: true,
    revGate: 500,
  },
  lambda: {
    kind: 'lambda',
    name: 'Lambda',
    short: 'λ',
    category: 'compute',
    blurb: 'Serverless. No idle cost, pays per invocation, scales itself — but cold starts sting when load jumps.',
    docsUrl: 'https://docs.aws.amazon.com/lambda/latest/dg/welcome.html',
    cost: 180,
    opCost: 0,
    capacity: 40,
    baseLatencyMs: 25,
    queueLen: 120,
    ports: [P('http-in', 'http', 'in', 'invoke'), P('jobs-in', 'jobs', 'in', 'events')],
    serves: ['api', 'job'],
    forwards: {},
    perServeCost: 0.003,
    research: 'serverless',
    special: 'lambda',
  },
  redis: {
    kind: 'redis',
    name: 'Redis',
    short: 'RDS',
    category: 'cache',
    blurb: 'In-memory cache with rich data structures. Answers 80% of reads in a millisecond; misses pass through.',
    docsUrl: 'https://redis.io/docs/latest/',
    cost: 180,
    opCost: 0.08,
    capacity: 400,
    baseLatencyMs: 1,
    queueLen: 500,
    ports: [P('data-in', 'data', 'in', 'GET/SET'), P('data-out', 'data', 'out', 'miss')],
    serves: [],
    forwards: { read: 'data', write: 'data' },
    hitRate: { read: 0.8 },
    research: 'caching',
  },
  memcached: {
    kind: 'memcached',
    name: 'Memcached',
    short: 'MCD',
    category: 'cache',
    blurb: 'A plain key-value cache: cheaper and higher raw throughput than Redis, but dumber — fewer reads land (68%).',
    docsUrl: 'https://github.com/memcached/memcached/wiki',
    cost: 110,
    opCost: 0.04,
    capacity: 600,
    baseLatencyMs: 1,
    queueLen: 600,
    ports: [P('data-in', 'data', 'in', 'get/set'), P('data-out', 'data', 'out', 'miss')],
    serves: [],
    forwards: { read: 'data', write: 'data' },
    hitRate: { read: 0.68 },
    research: 'caching',
  },
  postgres: {
    kind: 'postgres',
    name: 'Postgres',
    short: 'PG',
    category: 'data',
    blurb: 'The balanced open-source database — writes cost 3× a read. Protect it with caches.',
    docsUrl: 'https://www.postgresql.org/docs/current/',
    cost: 240,
    opCost: 0.15,
    capacity: 40,
    baseLatencyMs: 9,
    queueLen: 90,
    ports: [P('data-in', 'data', 'in', 'connections'), P('repl-out', 'repl', 'out', 'WAL')],
    serves: ['read', 'write'],
    forwards: {},
    capWeight: { write: 3 },
  },
  mysql: {
    kind: 'mysql',
    name: 'MySQL',
    short: 'MYS',
    category: 'data',
    blurb: 'The cheap workhorse: quick reads for less money, but write contention bites harder (writes cost 4×).',
    docsUrl: 'https://dev.mysql.com/doc/',
    cost: 190,
    opCost: 0.11,
    capacity: 45,
    baseLatencyMs: 8,
    queueLen: 90,
    ports: [P('data-in', 'data', 'in', 'connections'), P('repl-out', 'repl', 'out', 'binlog')],
    serves: ['read', 'write'],
    forwards: {},
    capWeight: { write: 4 },
    revGate: 200,
  },
  mssql: {
    kind: 'mssql',
    name: 'SQL Server',
    short: 'MSQ',
    category: 'data',
    blurb: 'The enterprise engine: strongest write concurrency in the catalog (2.5×) — and a licensing bill that never sleeps.',
    docsUrl: 'https://learn.microsoft.com/en-us/sql/sql-server/',
    cost: 320,
    opCost: 0.5,
    capacity: 60,
    baseLatencyMs: 7,
    queueLen: 110,
    ports: [P('data-in', 'data', 'in', 'connections'), P('repl-out', 'repl', 'out', 'AG replica')],
    serves: ['read', 'write'],
    forwards: {},
    capWeight: { write: 2.5 },
    revGate: 2500,
  },
  mongo: {
    kind: 'mongo',
    name: 'MongoDB',
    short: 'MGO',
    category: 'data',
    blurb: 'Document store: flexible schema, cheap writes (1.5×). No WAL port — read fan-out is not its story.',
    docsUrl: 'https://www.mongodb.com/docs/manual/',
    cost: 220,
    opCost: 0.13,
    capacity: 50,
    baseLatencyMs: 11,
    queueLen: 100,
    ports: [P('data-in', 'data', 'in', 'connections')],
    serves: ['read', 'write'],
    forwards: {},
    capWeight: { write: 1.5 },
    research: 'nosql',
  },
  elastic: {
    kind: 'elastic',
    name: 'Elasticsearch',
    short: 'ES',
    category: 'data',
    blurb: 'The search index: devours reads at 3× a replica\'s throughput, costs like it. Writes pass through to a real database.',
    docsUrl: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html',
    cost: 380,
    opCost: 0.35,
    capacity: 130,
    baseLatencyMs: 14,
    queueLen: 260,
    ports: [P('data-in', 'data', 'in', 'queries'), P('data-out', 'data', 'out', 'writes fwd')],
    serves: ['read'],
    forwards: { write: 'data' },
    research: 'nosql',
  },
  replica: {
    kind: 'replica',
    name: 'Read Replica',
    short: 'RR',
    category: 'data',
    blurb: 'Serves reads only. Needs a WAL/binlog link from a SQL primary; forwards writes back out.',
    docsUrl: 'https://www.postgresql.org/docs/current/high-availability.html',
    cost: 200,
    opCost: 0.1,
    capacity: 60,
    baseLatencyMs: 9,
    queueLen: 90,
    ports: [
      P('data-in', 'data', 'in', 'read pool'),
      P('repl-in', 'repl', 'in', 'WAL in'),
      P('data-out', 'data', 'out', 'writes fwd'),
    ],
    serves: ['read'],
    forwards: { write: 'data' },
    research: 'replicas',
  },
  queue: {
    kind: 'queue',
    name: 'Kafka',
    short: 'KFK',
    category: 'async',
    blurb: 'The durable log. Absorbs firehose spikes into a very deep buffer and drains at whatever your consumers can pull.',
    docsUrl: 'https://kafka.apache.org/documentation/',
    cost: 260,
    opCost: 0.1,
    capacity: 500,
    baseLatencyMs: 3,
    queueLen: 6000,
    ports: [P('jobs-in', 'jobs', 'in', 'produce'), P('jobs-out', 'jobs', 'out', 'consume')],
    serves: [],
    forwards: { job: 'jobs' },
    research: 'queues',
    special: 'queue',
  },
  rabbitmq: {
    kind: 'rabbitmq',
    name: 'RabbitMQ',
    short: 'RMQ',
    category: 'async',
    blurb: 'The classic broker: cheaper and snappier than Kafka, with a fraction of the buffer. Fine until the firehose.',
    docsUrl: 'https://www.rabbitmq.com/docs',
    cost: 150,
    opCost: 0.05,
    capacity: 280,
    baseLatencyMs: 2,
    queueLen: 1200,
    ports: [P('jobs-in', 'jobs', 'in', 'publish'), P('jobs-out', 'jobs', 'out', 'consume')],
    serves: [],
    forwards: { job: 'jobs' },
    research: 'queues',
    special: 'queue',
  },
  sqs: {
    kind: 'sqs',
    name: 'SQS',
    short: 'SQS',
    category: 'async',
    blurb: 'Managed queue: zero idle cost, bottomless buffer, a fee per message — and polling latency you can feel.',
    docsUrl: 'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html',
    cost: 80,
    opCost: 0,
    capacity: 350,
    baseLatencyMs: 15,
    queueLen: 100000,
    ports: [P('jobs-in', 'jobs', 'in', 'SendMessage'), P('jobs-out', 'jobs', 'out', 'ReceiveMessage')],
    serves: [],
    forwards: { job: 'jobs' },
    perServeCost: 0.0008,
    research: 'managed',
    special: 'queue',
  },
  worker: {
    kind: 'worker',
    name: 'Worker',
    short: 'WKR',
    category: 'async',
    blurb: 'Pulls jobs and grinds through them. Scale horizontally behind a queue.',
    docsUrl: 'https://docs.celeryq.dev/en/stable/',
    cost: 100,
    opCost: 0.07,
    capacity: 10,
    baseLatencyMs: 30,
    queueLen: 25,
    ports: [P('jobs-in', 'jobs', 'in', 'consume')],
    serves: ['job'],
    forwards: {},
    research: 'queues',
    zoneUnit: true,
  },
  prometheus: {
    kind: 'prometheus',
    name: 'Prometheus',
    short: 'PRM',
    category: 'observability',
    blurb: 'Scrapes your whole platform. Generates Research Points from served traffic; unlocks overlays.',
    docsUrl: 'https://prometheus.io/docs/introduction/overview/',
    cost: 120,
    opCost: 0.06,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [],
    serves: [],
    forwards: {},
    revGate: 150,
    special: 'metrics',
  },
  datadog: {
    kind: 'datadog',
    name: 'Datadog',
    short: 'DDG',
    category: 'observability',
    blurb: 'Observability as a SaaS: better insight per request than self-hosted (+75% RP weight) — invoiced accordingly.',
    docsUrl: 'https://docs.datadoghq.com/',
    cost: 260,
    opCost: 0.5,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [],
    serves: [],
    forwards: {},
    revGate: 800,
    special: 'metrics',
    rpWeight: BAL.datadogRpWeight,
  },
  grafana: {
    kind: 'grafana',
    name: 'Grafana',
    short: 'GRF',
    category: 'observability',
    blurb: 'Dashboards for the dashboards. +50% research rate and the cost overlay. One per company.',
    docsUrl: 'https://grafana.com/docs/grafana/latest/',
    cost: 180,
    opCost: 0.05,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [],
    serves: [],
    forwards: {},
    revGate: 600,
    singleton: true,
    special: 'grafana',
  },
  autoscaler: {
    kind: 'autoscaler',
    name: 'Autoscaler',
    short: 'ASG',
    category: 'automation',
    blurb: 'Wire its control port to a Zone: it adds and removes instances to track the zone\'s target utilization.',
    docsUrl: 'https://docs.aws.amazon.com/autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html',
    cost: 320,
    opCost: 0.05,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [P('ctl-out', 'control', 'out', 'scaling policy')],
    serves: [],
    forwards: {},
    research: 'autoscaling',
    special: 'autoscaler',
  },
  k8s: {
    kind: 'k8s',
    name: 'Kubernetes',
    short: 'K8S',
    category: 'automation',
    blurb: 'Orchestrator. Attached zones self-heal after incidents and pack 20% cheaper. One cluster is plenty.',
    docsUrl: 'https://kubernetes.io/docs/home/',
    cost: 450,
    opCost: 0.2,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [P('ctl-out', 'control', 'out', 'reconcile')],
    serves: [],
    forwards: {},
    research: 'orchestration',
    singleton: true,
    special: 'k8s',
  },
  cicd: {
    kind: 'cicd',
    name: 'GitHub Actions',
    short: 'CI',
    category: 'automation',
    blurb: 'Ship faster: provisioning drops from 10s to 3s and upgrades cost 12% less. One pipeline, global.',
    docsUrl: 'https://docs.github.com/en/actions',
    cost: 280,
    opCost: 0.08,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [],
    serves: [],
    forwards: {},
    research: 'containers',
    singleton: true,
    special: 'cicd',
  },
  stripe: {
    kind: 'stripe',
    name: 'Stripe Billing',
    short: 'BIL',
    category: 'automation',
    blurb: 'Automates invoicing. Revenue settles instantly (+2%) — stop clicking "Send invoices".',
    docsUrl: 'https://docs.stripe.com/billing',
    cost: 140,
    opCost: 0.02,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [],
    serves: [],
    forwards: {},
    revGate: 120,
    singleton: true,
    special: 'billing',
  },
};

export const PALETTE_ORDER: Category[] = [
  'ingress',
  'compute',
  'cache',
  'data',
  'async',
  'observability',
  'automation',
];

export function specOf(kind: NodeKind, zoneTemplate?: Exclude<NodeKind, 'zone'>): NodeSpec {
  if (kind === 'zone') return SPECS[zoneTemplate ?? 'app'];
  return SPECS[kind];
}

/** Nodes that behave as the stateful database tier (slow-query storms, dbmax metric, db-hot lesson). */
export const DB_KINDS: ReadonlySet<NodeKind> = new Set(['postgres', 'mysql', 'mssql', 'mongo', 'replica']);

/** Kinds a node can be replaced with in-place (edges kept where ports still match). */
export const REPLACE_MAP: Partial<Record<NodeKind, Exclude<NodeKind, 'zone'>[]>> = {
  nginx: ['lb', 'haproxy', 'apigw', 'cdn'],
  lb: ['haproxy', 'apigw', 'cdn'],
  haproxy: ['lb', 'apigw'],
  apigw: ['lb', 'haproxy'],
  app: ['lambda', 'spot'],
  spot: ['app', 'lambda'],
  worker: ['lambda'],
  redis: ['memcached', 'replica'],
  memcached: ['redis'],
  s3: ['cdn'],
  cdn: ['fastly', 'varnish'],
  fastly: ['cdn', 'varnish'],
  varnish: ['cdn', 'fastly'],
  postgres: ['mysql', 'mssql', 'mongo'],
  mysql: ['postgres', 'mssql', 'mongo'],
  mssql: ['postgres', 'mysql'],
  mongo: ['postgres', 'mysql'],
  elastic: ['replica'],
  replica: ['elastic'],
  queue: ['rabbitmq', 'sqs'],
  rabbitmq: ['queue', 'sqs'],
  sqs: ['queue', 'rabbitmq'],
  prometheus: ['datadog'],
  datadog: ['prometheus'],
};
