import type { Category, NodeKind, NodeSpec, PortDef } from '../engine/types';

// ---------------------------------------------------------------------------
// The infrastructure catalog. Every placeable node, its ports, its transform.
// Capacity is in weighted req/s; see capWeight for classes that cost more.
// ---------------------------------------------------------------------------

const P = (id: string, type: PortDef['type'], dir: PortDef['dir'], label: string): PortDef => ({
  id,
  type,
  dir,
  label,
});

export const CATEGORY_INFO: Record<Category, { label: string; color: string }> = {
  ingress: { label: 'Ingress / Network', color: '#58a6ff' },
  compute: { label: 'Compute', color: '#f0a44b' },
  data: { label: 'Data / Storage', color: '#a78bfa' },
  cache: { label: 'Cache / Edge', color: '#ec6ea5' },
  async: { label: 'Async / Queues', color: '#34d1bf' },
  observability: { label: 'Observability', color: '#7ce38b' },
  automation: { label: 'Automation', color: '#39c5cf' },
};

export const SPECS: Record<Exclude<NodeKind, 'zone'>, NodeSpec> = {
  users: {
    kind: 'users',
    name: 'Internet',
    short: 'WWW',
    category: 'ingress',
    blurb: 'Your users. Traffic originates here and grows with reputation. Cannot be removed.',
    cost: 0,
    opCost: 0,
    capacity: 1e9,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [P('http-out', 'http', 'out', 'egress')],
    serves: [],
    forwards: {},
    special: 'source',
  },
  nginx: {
    kind: 'nginx',
    name: 'Nginx',
    short: 'NGX',
    category: 'ingress',
    blurb: 'Web server. Serves static files itself, proxies everything else upstream.',
    cost: 60,
    opCost: 0.04,
    capacity: 12,
    baseLatencyMs: 5,
    queueLen: 30,
    ports: [P('http-in', 'http', 'in', 'listen :80'), P('http-out', 'http', 'out', 'upstream')],
    serves: ['static'],
    forwards: { api: 'http', read: 'http', write: 'http', job: 'http' },
    zoneUnit: true,
  },
  lb: {
    kind: 'lb',
    name: 'Load Balancer',
    short: 'ELB',
    category: 'ingress',
    blurb: 'Splits traffic across all connected upstreams by available headroom. Serves nothing itself.',
    cost: 140,
    opCost: 0.05,
    capacity: 150,
    baseLatencyMs: 1,
    queueLen: 200,
    ports: [P('http-in', 'http', 'in', 'vip'), P('http-out', 'http', 'out', 'targets')],
    serves: [],
    forwards: { static: 'http', api: 'http', read: 'http', write: 'http', job: 'http' },
    smartSplit: true,
    special: 'lb',
  },
  apigw: {
    kind: 'apigw',
    name: 'API Gateway',
    short: 'AGW',
    category: 'ingress',
    blurb: 'Rate-limits at the door: overload is shed as 429s (cheap) instead of timing out (costly).',
    cost: 220,
    opCost: 0.08,
    capacity: 250,
    baseLatencyMs: 2,
    queueLen: 260,
    ports: [P('http-in', 'http', 'in', 'edge'), P('http-out', 'http', 'out', 'routes')],
    serves: [],
    forwards: { static: 'http', api: 'http', read: 'http', write: 'http', job: 'http' },
    research: 'gateway',
    special: 'apigw',
  },
  cdn: {
    kind: 'cdn',
    name: 'Cloudflare CDN',
    short: 'CDN',
    category: 'cache',
    blurb: 'Edge cache. Serves 92% of static and 30% of reads at the edge; misses hit your origin.',
    cost: 300,
    opCost: 0.12,
    capacity: 1500,
    baseLatencyMs: 2,
    queueLen: 1500,
    ports: [P('http-in', 'http', 'in', 'edge'), P('http-out', 'http', 'out', 'origin')],
    serves: [],
    forwards: { static: 'http', api: 'http', read: 'http', write: 'http', job: 'http' },
    hitRate: { static: 0.92, read: 0.3 },
    research: 'cdn',
  },
  s3: {
    kind: 's3',
    name: 'S3 Bucket',
    short: 'S3',
    category: 'data',
    blurb: 'Object storage. Serves static at any volume for a tiny per-request fee. Slow-ish alone; pair with a CDN.',
    cost: 90,
    opCost: 0.02,
    capacity: 5000,
    baseLatencyMs: 45,
    queueLen: 4000,
    ports: [P('http-in', 'http', 'in', 'GET')],
    serves: ['static'],
    forwards: {},
    perServeCost: 0.0004,
    revGate: 300,
  },
  app: {
    kind: 'app',
    name: 'App Server',
    short: 'EC2',
    category: 'compute',
    blurb: 'Your Docker container on an EC2-style box. Completes API calls; reads/writes go out the DB port, heavy jobs out the async port.',
    cost: 120,
    opCost: 0.1,
    capacity: 15,
    baseLatencyMs: 12,
    queueLen: 40,
    ports: [
      P('http-in', 'http', 'in', 'requests'),
      P('data-out', 'data', 'out', 'db pool'),
      P('jobs-out', 'jobs', 'out', 'enqueue'),
    ],
    serves: ['static', 'api'],
    forwards: { read: 'data', write: 'data', job: 'jobs' },
    capWeight: { static: 0.6 },
    zoneUnit: true,
  },
  lambda: {
    kind: 'lambda',
    name: 'Lambda',
    short: 'λ',
    category: 'compute',
    blurb: 'Serverless. No idle cost, pays per invocation, scales itself — but cold starts sting when load jumps.',
    cost: 180,
    opCost: 0,
    capacity: 40,
    baseLatencyMs: 25,
    queueLen: 120,
    ports: [P('http-in', 'http', 'in', 'invoke'), P('jobs-in', 'jobs', 'in', 'events')],
    serves: ['api', 'job'],
    forwards: {},
    perServeCost: 0.003,
    research: 'serverless',
    special: 'lambda',
  },
  redis: {
    kind: 'redis',
    name: 'Redis',
    short: 'RDS',
    category: 'cache',
    blurb: 'In-memory cache. Answers 80% of reads in a millisecond; misses pass through to the database.',
    cost: 180,
    opCost: 0.08,
    capacity: 400,
    baseLatencyMs: 1,
    queueLen: 500,
    ports: [P('data-in', 'data', 'in', 'GET/SET'), P('data-out', 'data', 'out', 'miss')],
    serves: [],
    forwards: { read: 'data', write: 'data' },
    hitRate: { read: 0.8 },
    research: 'caching',
  },
  postgres: {
    kind: 'postgres',
    name: 'Postgres',
    short: 'PG',
    category: 'data',
    blurb: 'The database. Shared, contended, and precious — writes cost 3× a read. Protect it with caches.',
    cost: 240,
    opCost: 0.15,
    capacity: 40,
    baseLatencyMs: 9,
    queueLen: 90,
    ports: [P('data-in', 'data', 'in', 'connections'), P('repl-out', 'repl', 'out', 'WAL')],
    serves: ['read', 'write'],
    forwards: {},
    capWeight: { write: 3 },
  },
  replica: {
    kind: 'replica',
    name: 'Read Replica',
    short: 'RR',
    category: 'data',
    blurb: 'Serves reads only. Needs a WAL link from a Postgres primary; forwards writes back out.',
    cost: 200,
    opCost: 0.1,
    capacity: 60,
    baseLatencyMs: 9,
    queueLen: 90,
    ports: [
      P('data-in', 'data', 'in', 'read pool'),
      P('repl-in', 'repl', 'in', 'WAL in'),
      P('data-out', 'data', 'out', 'writes fwd'),
    ],
    serves: ['read'],
    forwards: { write: 'data' },
    research: 'replicas',
  },
  queue: {
    kind: 'queue',
    name: 'Kafka',
    short: 'KFK',
    category: 'async',
    blurb: 'Message queue. Absorbs spikes into a deep buffer and drains at whatever your consumers can pull.',
    cost: 260,
    opCost: 0.1,
    capacity: 500,
    baseLatencyMs: 3,
    queueLen: 6000,
    ports: [P('jobs-in', 'jobs', 'in', 'produce'), P('jobs-out', 'jobs', 'out', 'consume')],
    serves: [],
    forwards: { job: 'jobs' },
    research: 'queues',
    special: 'queue',
  },
  worker: {
    kind: 'worker',
    name: 'Worker',
    short: 'WKR',
    category: 'async',
    blurb: 'Pulls jobs and grinds through them. Scale horizontally behind a queue.',
    cost: 100,
    opCost: 0.07,
    capacity: 10,
    baseLatencyMs: 30,
    queueLen: 25,
    ports: [P('jobs-in', 'jobs', 'in', 'consume')],
    serves: ['job'],
    forwards: {},
    research: 'queues',
    zoneUnit: true,
  },
  prometheus: {
    kind: 'prometheus',
    name: 'Prometheus',
    short: 'PRM',
    category: 'observability',
    blurb: 'Scrapes your whole platform. Generates Research Points from served traffic; unlocks overlays.',
    cost: 120,
    opCost: 0.06,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [],
    serves: [],
    forwards: {},
    revGate: 150,
    special: 'metrics',
  },
  grafana: {
    kind: 'grafana',
    name: 'Grafana',
    short: 'GRF',
    category: 'observability',
    blurb: 'Dashboards for the dashboards. +60% research rate and the cost overlay. One per company.',
    cost: 180,
    opCost: 0.05,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [],
    serves: [],
    forwards: {},
    revGate: 600,
    singleton: true,
    special: 'grafana',
  },
  autoscaler: {
    kind: 'autoscaler',
    name: 'Autoscaler',
    short: 'ASG',
    category: 'automation',
    blurb: 'Wire its control port to a Zone: it adds and removes instances to track the zone\'s target utilization.',
    cost: 320,
    opCost: 0.05,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [P('ctl-out', 'control', 'out', 'scaling policy')],
    serves: [],
    forwards: {},
    research: 'autoscaling',
    special: 'autoscaler',
  },
  k8s: {
    kind: 'k8s',
    name: 'Kubernetes',
    short: 'K8S',
    category: 'automation',
    blurb: 'Orchestrator. Attached zones self-heal after incidents and pack 20% cheaper. One cluster is plenty.',
    cost: 450,
    opCost: 0.2,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [P('ctl-out', 'control', 'out', 'reconcile')],
    serves: [],
    forwards: {},
    research: 'orchestration',
    singleton: true,
    special: 'k8s',
  },
  cicd: {
    kind: 'cicd',
    name: 'GitHub Actions',
    short: 'CI',
    category: 'automation',
    blurb: 'Ship faster: provisioning drops from 10s to 3s and upgrades cost 12% less. One pipeline, global.',
    cost: 280,
    opCost: 0.08,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [],
    serves: [],
    forwards: {},
    research: 'containers',
    singleton: true,
    special: 'cicd',
  },
  stripe: {
    kind: 'stripe',
    name: 'Stripe Billing',
    short: 'BIL',
    category: 'automation',
    blurb: 'Automates invoicing. Revenue settles instantly (+2%) — stop clicking "Send invoices".',
    cost: 140,
    opCost: 0.02,
    capacity: 0,
    baseLatencyMs: 0,
    queueLen: 0,
    ports: [],
    serves: [],
    forwards: {},
    revGate: 120,
    singleton: true,
    special: 'billing',
  },
};

export const PALETTE_ORDER: Category[] = [
  'ingress',
  'compute',
  'cache',
  'data',
  'async',
  'observability',
  'automation',
];

export function specOf(kind: NodeKind, zoneTemplate?: Exclude<NodeKind, 'zone'>): NodeSpec {
  if (kind === 'zone') return SPECS[zoneTemplate ?? 'app'];
  return SPECS[kind];
}

/** Kinds a node can be replaced with in-place (edges kept where ports still match). */
export const REPLACE_MAP: Partial<Record<NodeKind, Exclude<NodeKind, 'zone'>[]>> = {
  nginx: ['lb', 'apigw', 'cdn'],
  lb: ['apigw', 'cdn'],
  apigw: ['lb'],
  app: ['lambda'],
  worker: ['lambda'],
  redis: ['replica'],
  s3: ['cdn'],
};
