import type { ResearchDef } from '../engine/types';

// The tech tree. Costs are Research Points (generated by Prometheus/Grafana).
// Effects are applied in store.buyResearch + read by the engine via owned ids.
export const RESEARCH: ResearchDef[] = [
  {
    id: 'containers',
    name: 'Containers',
    icon: '▣',
    desc: 'Docker-ize the fleet. Unlocks the CI/CD Pipeline node (fast deploys, cheaper upgrades).',
    cost: 10,
    deps: [],
    grants: ['Unlocks CI/CD Pipeline', 'Prereq for orchestration & autoscaling'],
  },
  {
    id: 'caching',
    name: 'Caching Layers',
    icon: '⚡',
    desc: 'Memcached walked so Redis could run. Unlocks the Redis node and the Accounts tier.',
    cost: 12,
    deps: [],
    grants: ['Unlocks Redis', 'Unlocks tier: Accounts + Database'],
  },
  {
    id: 'gateway',
    name: 'API Gateway',
    icon: '⛩',
    desc: 'Central ingress with rate limiting. Overload becomes graceful 429s instead of timeouts.',
    cost: 25,
    deps: [],
    grants: ['Unlocks API Gateway'],
  },
  {
    id: 'autoscaling',
    name: 'Autoscaling',
    icon: '⇕',
    desc: 'Capacity as a policy, not a purchase. Unlocks the Autoscaler node and the Zone tool.',
    cost: 30,
    deps: ['containers'],
    grants: ['Unlocks Autoscaler', 'Unlocks Zone tool (declarative capacity pools)'],
  },
  {
    id: 'queues',
    name: 'Message Queues',
    icon: '☰',
    desc: 'Stop provisioning for peak. Unlocks Kafka + Workers and the Search/Analytics tier.',
    cost: 45,
    deps: [],
    grants: ['Unlocks Kafka & Worker', 'Unlocks tier: Search / Analytics'],
  },
  {
    id: 'replicas',
    name: 'Read Replicas',
    icon: '⎘',
    desc: 'Scale reads past a single primary. Unlocks the Read Replica node.',
    cost: 60,
    deps: ['caching'],
    grants: ['Unlocks Read Replica'],
  },
  {
    id: 'cdn',
    name: 'CDN / Edge',
    icon: '◍',
    desc: 'Push bytes to the edge. Unlocks the CDN node and the Real-time tier.',
    cost: 55,
    deps: [],
    grants: ['Unlocks CDN', 'Unlocks tier: Real-time Platform (needs Seed round)'],
  },
  {
    id: 'orchestration',
    name: 'Orchestration',
    icon: '⎈',
    desc: 'Kubernetes. Attached zones self-heal and bin-pack 20% cheaper.',
    cost: 90,
    deps: ['containers'],
    grants: ['Unlocks Kubernetes'],
  },
  {
    id: 'obs2',
    name: 'Distributed Tracing',
    icon: '◉',
    desc: 'OpenTelemetry everywhere. +50% research rate; unlocks error & cache-hit overlays.',
    cost: 70,
    deps: [],
    grants: ['+50% RP rate', 'Unlocks Errors + Cache overlays'],
  },
  {
    id: 'serverless',
    name: 'Serverless',
    icon: 'λ',
    desc: 'Functions, not fleets. Unlocks Lambda: zero idle cost, per-invocation pricing, cold starts.',
    cost: 110,
    deps: ['gateway'],
    grants: ['Unlocks Lambda'],
  },
  {
    id: 'mesh',
    name: 'Service Mesh',
    icon: '✳',
    desc: 'Sidecars with opinions. Every node splits traffic by headroom (least-loaded), +5% capacity.',
    cost: 160,
    deps: ['orchestration'],
    grants: ['Smart (headroom) routing everywhere', '+5% global capacity'],
  },
  {
    id: 'multiregion',
    name: 'Multi-region',
    icon: '⊕',
    desc: 'us-east is not the world. Region outages degrade redundant regions instead of killing them.',
    cost: 220,
    deps: ['mesh'],
    grants: ['Redundancy policy fully absorbs outages', 'Region policies +1 free'],
  },
  {
    id: 'mlpipe',
    name: 'ML Pipelines',
    icon: '⬡',
    desc: 'GPUs go brrr. Unlocks the ML Inference tier; workers gain +50% capacity.',
    cost: 320,
    deps: ['queues'],
    grants: ['Unlocks tier: ML Inference (needs Series A)', 'Workers +50% capacity'],
  },
];

export const researchById = new Map(RESEARCH.map((r) => [r.id, r]));

/** Column layout for the tree panel: depth = longest dep chain. */
export function researchDepth(id: string): number {
  const def = researchById.get(id);
  if (!def || def.deps.length === 0) return 0;
  return 1 + Math.max(...def.deps.map(researchDepth));
}
